# Generated by Django 4.2.5 on 2023-10-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecode',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
