# Generated by Django 4.2.5 on 2023-10-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_post_filepost_post_file_post_img_post_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='acceptResponse',
            field=models.BooleanField(default=False),
        ),
    ]
